### ISSUE TITLE
xcode7.0.1でStandaredDemoをコンパイルするとエラーが出てコンパイルできません

### ISSUE THREAD

**Issue by norifujimura** [OmronSensingEggProject/HVC_C2W_SDK_iOS#1]
xcode7.0.1でStandaredDemoをコンパイルすると以下のエラーが出てコンパイルできません。どのような対応をすると動くようにできますか？

Ld /Users/nori/Library/Developer/Xcode/DerivedData/StandardDemo-bvriryjsrznlrwbrfvjwjpaywrha/Build/Products/Debug-iphonesimulator/StandardDemo.app/StandardDemo normal i386
    cd /Users/nori/Documents/iOS/StandardDemo
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/nori/Library/Developer/Xcode/DerivedData/StandardDemo-bvriryjsrznlrwbrfvjwjpaywrha/Build/Products/Debug-iphonesimulator -L/Users/nori/Documents/iOS/StandardDemo/StandardDemo/lib -L/Users/s_fuku/Desktop/ipcam/c2wsdk/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib -F/Users/nori/Library/Developer/Xcode/DerivedData/StandardDemo-bvriryjsrznlrwbrfvjwjpaywrha/Build/Products/Debug-iphonesimulator -filelist /Users/nori/Library/Developer/Xcode/DerivedData/StandardDemo-bvriryjsrznlrwbrfvjwjpaywrha/Build/Intermediates/StandardDemo.build/Debug-iphonesimulator/StandardDemo.build/Objects-normal/i386/StandardDemo.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=7.0 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -lHvcOi -lstdc++.6.0.9 -lc2w -lHVCW -lz.1 -Xlinker -dependency_info -Xlinker /Users/nori/Library/Developer/Xcode/DerivedData/StandardDemo-bvriryjsrznlrwbrfvjwjpaywrha/Build/Intermediates/StandardDemo.build/Debug-iphonesimulator/StandardDemo.build/Objects-normal/i386/StandardDemo_dependency_info.dat -o /Users/nori/Library/Developer/Xcode/DerivedData/StandardDemo-bvriryjsrznlrwbrfvjwjpaywrha/Build/Products/Debug-iphonesimulator/StandardDemo.app/StandardDemo

ld: warning: directory not found for option '-L/Users/s_fuku/Desktop/ipcam/c2wsdk/lib'
ld: warning: ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libstdc++.6.0.9.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libstdc++.6.0.9.tbdignoring file /Users/nori/Documents/iOS/StandardDemo/StandardDemo/lib/libHvcOi.a, missing required architecture i386 in file /Users/nori/Documents/iOS/StandardDemo/StandardDemo/lib/libHvcOi.a (3 slices)

ld: warning: ignoring file /Users/nori/Documents/iOS/StandardDemo/StandardDemo/lib/libc2w.a, missing required architecture i386 in file /Users/nori/Documents/iOS/StandardDemo/StandardDemo/lib/libc2w.a (2 slices)
ld: warning: ignoring file /Users/nori/Documents/iOS/StandardDemo/StandardDemo/lib/libHVCW.a, missing required architecture i386 in file /Users/nori/Documents/iOS/StandardDemo/StandardDemo/lib/libHVCW.a (3 slices)
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libz.1.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libz.1.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libobjc.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libobjc.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture i386:
  "_HVCW_ALBUM_Register", referenced from:
      -[OpeningViewController registrationBtn:] in OpeningViewController.o
  "_HVCW_ALBUM_Save", referenced from:
      -[OpeningViewController registrationBtn:] in OpeningViewController.o
  "_HVCW_Connect", referenced from:
      -[OpeningViewController connectCamera:] in OpeningViewController.o
  "_HVCW_CreateHandle", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
  "_HVCW_DeleteHandle", referenced from:
      -[AppDelegate applicationWillTerminate:] in AppDelegate.o
  "_HVCW_Disconnect", referenced from:
      -[OpeningViewController disconnectCamera] in OpeningViewController.o
  "_HVCW_GenerateDataSoundFile", referenced from:
      -[LoginContentsViewController createDOVFile] in LoginContentsViewController.o
  "_HVCW_GetCameraMacAddress", referenced from:
      -[OpeningViewController connectCamera:] in OpeningViewController.o
  "_HVCW_GetCameraVersion", referenced from:
      -[OpeningViewController connectCamera:] in OpeningViewController.o
  "_HVCW_GetConnectionType", referenced from:
      -[OpeningViewController connectCamera:] in OpeningViewController.o
  "_HVCW_GetVersion", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
  "_HVCW_OKAO_Execute", referenced from:
      -[RunningViewController OKAO_Execute] in RunningViewController.o
  "_HVCW_OKAO_GetSizeRange", referenced from:
      -[ExecParamTableViewController viewDidLoad] in ExecParamTableViewController.o
  "_HVCW_OKAO_GetThreshold", referenced from:
      -[ExecParamTableViewController viewDidLoad] in ExecParamTableViewController.o
  "_HVCW_OKAO_SetSizeRange", referenced from:
      -[ExecParamTableViewController viewWillDisappear:] in ExecParamTableViewController.o
  "_HVCW_OKAO_SetThreshold", referenced from:
      -[ExecParamTableViewController viewWillDisappear:] in ExecParamTableViewController.o
  "_HVCW_SetAppID", referenced from:
      -[OpeningViewController connectCamera:] in OpeningViewController.o
  "_HVCW_SetOkaoMode", referenced from:
      -[OpeningViewController connectCamera:] in OpeningViewController.o
  "__Block_copy", referenced from:
      __arclite_objc_retainBlock(objc_object*) in libarclite_iphonesimulator.a(arclite.o)
  "__Block_object_assign", referenced from:
      ___copy_helper_block_116 in HVCWebAPIManager.o
  "__Block_object_dispose", referenced from:
      +[HVCWebAPIManager allocWithZone:] in HVCWebAPIManager.o
      ___destroy_helper_block_117 in HVCWebAPIManager.o
  "__DefaultRuneLocale", referenced from:
      scanMangledField(char const*&, char const*, char const*&, int&) in libarclite_iphonesimulator.a(arclite.o)
  "__NSConcreteStackBlock", referenced from:
      -[RunningViewController viewDidAppear:] in RunningViewController.o
      -[RunningViewController OKAO_Execute] in RunningViewController.o
      -[OpeningViewController viewDidAppear:] in OpeningViewController.o
      -[OpeningViewController connectCamera:] in OpeningViewController.o
      -[OpeningViewController disconnectCamera] in OpeningViewController.o
      -[OpeningViewController PushConnectButton:] in OpeningViewController.o
      -[OpeningViewController setStatusLabel:] in OpeningViewController.o
      ...
      -[RunningViewController viewDidAppear:] in RunningViewController.o
      -[RunningViewController OKAO_Execute] in RunningViewController.o
      -[OpeningViewController viewDidAppear:] in OpeningViewController.o
      -[OpeningViewController connectCamera:] in OpeningViewController.o
      -[OpeningViewController disconnectCamera] in OpeningViewController.o
      -[OpeningViewController PushConnectButton:] in OpeningViewController.o
      -[OpeningViewController setStatusLabel:] in OpeningViewController.o
      ...
      -[RunningViewController viewDidAppear:] in RunningViewController.o
      -[RunningViewController OKAO_Execute] in RunningViewController.o
      -[OpeningViewController viewDidAppear:] in OpeningViewController.o
      -[OpeningViewController connectCamera:] in OpeningViewController.o
      -[OpeningViewController disconnectCamera] in OpeningViewController.o
      -[OpeningViewController PushConnectButton:] in OpeningViewController.o
      -[OpeningViewController setStatusLabel:] in OpeningViewController.o
      ...
      -[RunningViewController viewDidAppear:] in RunningViewController.o
      -[RunningViewController OKAO_Execute] in RunningViewController.o
      -[OpeningViewController viewDidAppear:] in OpeningViewController.o
      -[OpeningViewController connectCamera:] in OpeningViewController.o
      -[OpeningViewController disconnectCamera] in OpeningViewController.o
      -[OpeningViewController PushConnectButton:] in OpeningViewController.o
      -[OpeningViewController setStatusLabel:] in OpeningViewController.o
      ...
  "___stack_chk_fail", referenced from:
      -[RunningViewController FinishExec:useFunction:] in RunningViewController.o
      -[PCMplayer playPCMFileWithPath:] in PCMPlayer.o
      +[Reachability reachabilityForInternetConnection] in Reachability.o
      +[Reachability reachabilityForLocalWiFi] in Reachability.o
      -[OpeningViewController connectCamera:] in OpeningViewController.o
      -[OpeningViewController registrationBtn:] in OpeningViewController.o
      ___44-[LoginContentsViewController getCameraList]_block_invoke in LoginContentsViewController.o
      ...
  "___stack_chk_guard", referenced from:
      -[RunningViewController FinishExec:useFunction:] in RunningViewController.o
      -[PCMplayer playPCMFileWithPath:] in PCMPlayer.o
      +[Reachability reachabilityForInternetConnection] in Reachability.o
      +[Reachability reachabilityForLocalWiFi] in Reachability.o
      -[OpeningViewController connectCamera:] in OpeningViewController.o
      -[OpeningViewController registrationBtn:] in OpeningViewController.o
      ___44-[LoginContentsViewController getCameraList]_block_invoke in LoginContentsViewController.o
      ...
      -[RunningViewController FinishExec:useFunction:] in RunningViewController.o
      -[PCMplayer playPCMFileWithPath:] in PCMPlayer.o
      +[Reachability reachabilityForInternetConnection] in Reachability.o
      +[Reachability reachabilityForLocalWiFi] in Reachability.o
      -[OpeningViewController connectCamera:] in OpeningViewController.o
      -[OpeningViewController registrationBtn:] in OpeningViewController.o
      ___44-[LoginContentsViewController getCameraList]_block_invoke in LoginContentsViewController.o
      ...
      -[RunningViewController FinishExec:useFunction:] in RunningViewController.o
      -[PCMplayer playPCMFileWithPath:] in PCMPlayer.o
      +[Reachability reachabilityForInternetConnection] in Reachability.o
      +[Reachability reachabilityForLocalWiFi] in Reachability.o
      -[OpeningViewController connectCamera:] in OpeningViewController.o
      -[OpeningViewController registrationBtn:] in OpeningViewController.o
      ___44-[LoginContentsViewController getCameraList]_block_invoke in LoginContentsViewController.o
      ...
      -[RunningViewController FinishExec:useFunction:] in RunningViewController.o
      -[PCMplayer playPCMFileWithPath:] in PCMPlayer.o
      +[Reachability reachabilityForInternetConnection] in Reachability.o
      +[Reachability reachabilityForLocalWiFi] in Reachability.o
      -[OpeningViewController connectCamera:] in OpeningViewController.o
      -[OpeningViewController registrationBtn:] in OpeningViewController.o
      ___44-[LoginContentsViewController getCameraList]_block_invoke in LoginContentsViewController.o
      ...
      -[RunningViewController FinishExec:useFunction:] in RunningViewController.o
      -[PCMplayer playPCMFileWithPath:] in PCMPlayer.o
      +[Reachability reachabilityForInternetConnection] in Reachability.o
      +[Reachability reachabilityForLocalWiFi] in Reachability.o
      -[OpeningViewController connectCamera:] in OpeningViewController.o
      -[OpeningViewController registrationBtn:] in OpeningViewController.o
      ___44-[LoginContentsViewController getCameraList]_block_invoke in LoginContentsViewController.o
      ...
      -[RunningViewController FinishExec:useFunction:] in RunningViewController.o
      -[PCMplayer playPCMFileWithPath:] in PCMPlayer.o
      +[Reachability reachabilityForInternetConnection] in Reachability.o
      +[Reachability reachabilityForLocalWiFi] in Reachability.o
      -[OpeningViewController connectCamera:] in OpeningViewController.o
      -[OpeningViewController registrationBtn:] in OpeningViewController.o
      ___44-[LoginContentsViewController getCameraList]_block_invoke in LoginContentsViewController.o
      ...
      -[RunningViewController FinishExec:useFunction:] in RunningViewController.o
      -[PCMplayer playPCMFileWithPath:] in PCMPlayer.o
      +[Reachability reachabilityForInternetConnection] in Reachability.o
      +[Reachability reachabilityForLocalWiFi] in Reachability.o
      -[OpeningViewController connectCamera:] in OpeningViewController.o
      -[OpeningViewController registrationBtn:] in OpeningViewController.o
      ___44-[LoginContentsViewController getCameraList]_block_invoke in LoginContentsViewController.o
      ...
      ...
  "__dispatch_main_q", referenced from:
      -[OpeningViewController viewDidAppear:] in OpeningViewController.o
      -[OpeningViewController connectCamera:] in OpeningViewController.o
      -[OpeningViewController disconnectCamera] in OpeningViewController.o
      -[OpeningViewController setStatusLabel:] in OpeningViewController.o
      -[OpeningViewController setTypeLabel:] in OpeningViewController.o
      -[OpeningViewController setVersionLabel:] in OpeningViewController.o
      -[LoginContentsViewController viewDidAppear:] in LoginContentsViewController.o
      ...
      -[OpeningViewController viewDidAppear:] in OpeningViewController.o
      -[OpeningViewController connectCamera:] in OpeningViewController.o
      -[OpeningViewController disconnectCamera] in OpeningViewController.o
      -[OpeningViewController setStatusLabel:] in OpeningViewController.o
      -[OpeningViewController setTypeLabel:] in OpeningViewController.o
      -[OpeningViewController setVersionLabel:] in OpeningViewController.o
      -[LoginContentsViewController viewDidAppear:] in LoginContentsViewController.o
      ...
  "__dyld_register_func_for_add_image", referenced from:
      __ARCLite__load() in libarclite_iphonesimulator.a(arclite.o)
  "_asprintf", referenced from:
      copySwiftV1MangledName(char const*, bool) in libarclite_iphonesimulator.a(arclite.o)
      demangledName(char const*, bool) in libarclite_iphonesimulator.a(arclite.o)
  "_bzero", referenced from:
      __arclite_objc_readClassPair(objc_class*, objc_image_info const*) in libarclite_iphonesimulator.a(arclite.o)
      allocateMaybeSwift(glue_swift_class_t*, unsigned long) in libarclite_iphonesimulator.a(arclite.o)
  "_calloc", referenced from:
      __arclite_object_copy(objc_object*, unsigned long) in libarclite_iphonesimulator.a(arclite.o)
      allocateMaybeSwift(glue_swift_class_t*, unsigned long) in libarclite_iphonesimulator.a(arclite.o)
  "_dispatch_async", referenced from:
      -[OpeningViewController viewDidAppear:] in OpeningViewController.o
      -[OpeningViewController connectCamera:] in OpeningViewController.o
      -[OpeningViewController disconnectCamera] in OpeningViewController.o
      -[OpeningViewController setStatusLabel:] in OpeningViewController.o
      -[OpeningViewController setTypeLabel:] in OpeningViewController.o
      -[OpeningViewController setVersionLabel:] in OpeningViewController.o
      -[LoginContentsViewController viewDidAppear:] in LoginContentsViewController.o
      ...
  "_dispatch_once", referenced from:
      +[HVCWebAPIManager sharedInstance] in HVCWebAPIManager.o
      +[HVCWebAPIManager allocWithZone:] in HVCWebAPIManager.o
  "_fopen", referenced from:
      -[PCMplayer playPCMFileWithPath:] in PCMPlayer.o
  "_fread", referenced from:
      -[PCMplayer readPacketsIntoBuffer:andQueue:] in PCMPlayer.o
  "_free", referenced from:
      __arclite_objc_getClass(char const*) in libarclite_iphonesimulator.a(arclite.o)
      __arclite_objc_getMetaClass(char const*) in libarclite_iphonesimulator.a(arclite.o)
      __arclite_objc_getRequiredClass(char const*) in libarclite_iphonesimulator.a(arclite.o)
      __arclite_objc_lookUpClass(char const*) in libarclite_iphonesimulator.a(arclite.o)
      __arclite_objc_getProtocol(char const*) in libarclite_iphonesimulator.a(arclite.o)
      transcribeProperties(objc_class*, glue_class_ro_t*) in libarclite_iphonesimulator.a(arclite.o)
      fixStringForCoreData(objc_object*) in libarclite_iphonesimulator.a(arclite.o)
      ...
  "_hash_create", referenced from:
      demangledName(char const*, bool) in libarclite_iphonesimulator.a(arclite.o)
  "_hash_search", referenced from:
      demangledName(char const*, bool) in libarclite_iphonesimulator.a(arclite.o)
  "_malloc", referenced from:
      -[PCMplayer readPacketsIntoBuffer:andQueue:] in PCMPlayer.o
      fixStringForCoreData(objc_object*) in libarclite_iphonesimulator.a(arclite.o)
  "_memcmp", referenced from:
      copySwiftV1MangledName(char const*, bool) in libarclite_iphonesimulator.a(arclite.o)
  "_memcpy", referenced from:
      -[RunningViewController OKAO_Execute] in RunningViewController.o
      -[PCMplayer readPacketsIntoBuffer:andQueue:] in PCMPlayer.o
      __arclite_object_copy(objc_object*, unsigned long) in libarclite_iphonesimulator.a(arclite.o)
      allocateMaybeSwift(glue_swift_class_t*, unsigned long) in libarclite_iphonesimulator.a(arclite.o)
  "_memset", referenced from:
      -[RunningViewController viewDidLoad] in RunningViewController.o
      -[RunningViewController FinishExec:useFunction:] in RunningViewController.o
      +[Reachability reachabilityForInternetConnection] in Reachability.o
      +[Reachability reachabilityForLocalWiFi] in Reachability.o
      ___44-[LoginContentsViewController getCameraList]_block_invoke in LoginContentsViewController.o
      -[HVCWebAPIManager connectionDidFinishLoading:] in HVCWebAPIManager.o
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
      ...
  "_printf", referenced from:
      -[PCMplayer playPCMFileWithPath:] in PCMPlayer.o
  "_pthread_mutex_lock", referenced from:
      demangledName(char const*, bool) in libarclite_iphonesimulator.a(arclite.o)
  "_pthread_mutex_unlock", referenced from:
      demangledName(char const*, bool) in libarclite_iphonesimulator.a(arclite.o)
  "_sleep", referenced from:
      -[OpeningViewController registrationBtn:] in OpeningViewController.o
  "_strcmp", referenced from:
      patch_lazy_pointers(mach_header const*, patch_t*, unsigned long) in libarclite_iphonesimulator.a(arclite.o)
      demangledName(char const*, bool) in libarclite_iphonesimulator.a(arclite.o)
  "_strlen", referenced from:
      demangledName(char const*, bool) in libarclite_iphonesimulator.a(arclite.o)
  "_strncmp", referenced from:
      demangledName(char const*, bool) in libarclite_iphonesimulator.a(arclite.o)
  "_uname", referenced from:
      -[HVCWebAPIManager loginWithEmail:password:completed:] in HVCWebAPIManager.o
      -[HVCWebAPIManager loginWithSNSInfo:completed:] in HVCWebAPIManager.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by s-manabe** [comment]
i386でビルドされており、Simulatorで動かそうとされているかと存じます。
現在サポートしているのはARM系マシンのみで、本SDKを動かすためにはiPhoneかiPadの実機が必要です。

**Comment by norifujimura** [comment]
アドバイスありがとうございます。iPhoneのOSを9.1にしていたので、xcode7.1でコンパイルしてiPhone上でデモアプリを動かしました。
